CREATE TABLE Site(
   NOSITE INT,
   LIBELLE VARCHAR(50),
   PRIMARY KEY(NOSITE)
);

CREATE TABLE CENTRETRAITEMENT(
   NOCENTRE INT,
   NOMCENTRE VARCHAR(50),
   NORUECENTRE INT,
   CPOSTALCENTRE INT,
   VILLECENTRE VARCHAR(50),
   PRIMARY KEY(NOCENTRE)
);

CREATE TABLE Entreprise(
   SIRET INT,
   RAISONSOCIALE VARCHAR(50),
   NORUEENTR INT,
   RUEENTRE VARCHAR(50),
   CPOSTALENTR INT,
   VILLEENTRE VARCHAR(50),
   NOTEL CHAR(10),
   CONTACT VARCHAR(50),
   PRIMARY KEY(SIRET)
);

CREATE TABLE FONCTION(
   NOFONCTION INT,
   LIBELLE VARCHAR(50),
   PRIMARY KEY(NOFONCTION)
);

CREATE TABLE TYPEDECHET(
   NOTYPEDECHET INT,
   NOMTYPEDECHET VARCHAR(50),
   NIV_DANGER INT,
   TARIF_FORFETAIRE DECIMAL(15,2),
   TARIF_LOT DECIMAL(15,2),
   PRIMARY KEY(NOTYPEDECHET)
);

CREATE TABLE MARQUE(
   NOMARQUE INT,
   RAISONSOCIALE VARCHAR(50),
   PRIMARY KEY(NOMARQUE)
);

CREATE TABLE MODELE(
   NOMODELE INT,
   NOMMODELE VARCHAR(50),
   NOMARQUE INT NOT NULL,
   PRIMARY KEY(NOMODELE),
   FOREIGN KEY(NOMARQUE) REFERENCES MARQUE(NOMARQUE)
);

CREATE TABLE CAMION(
   NOIMMACTRIC CHAR(10),
   DATEACHAT DATE,
   CAPACITE INT,
   NOMODELE INT NOT NULL,
   PRIMARY KEY(NOIMMACTRIC),
   FOREIGN KEY(NOMODELE) REFERENCES MODELE(NOMODELE)
);

CREATE TABLE TOURNEE(
   NOTOURNEE INT,
   DATETOURNEE DATE,
   NOIMMACTRIC CHAR(10) NOT NULL,
   PRIMARY KEY(NOTOURNEE),
   FOREIGN KEY(NOIMMACTRIC) REFERENCES CAMION(NOIMMACTRIC)
);

CREATE TABLE Demande(
   NODEMANDE VARCHAR(50),
   DATEDEMANDE DATE,
   DATEENLEVEMENT DATE,
   SIRET INT,
   WEB_O_N LOGICAL,
   SIRET_1 INT NOT NULL,
   NOTOURNEE INT,
   PRIMARY KEY(NODEMANDE),
   FOREIGN KEY(SIRET_1) REFERENCES Entreprise(SIRET),
   FOREIGN KEY(NOTOURNEE) REFERENCES TOURNEE(NOTOURNEE)
);

CREATE TABLE Employe(
   NOEMPLOYE INT,
   Nom VARCHAR(50),
   Prenom VARCHAR(50),
   Datenaiss DATE,
   SALAIRE VARCHAR(50),
   DATEEMBAUCHE DATE,
   NOTOURNEE INT NOT NULL,
   NOFONCTION INT NOT NULL,
   NOSITE INT NOT NULL,
   PRIMARY KEY(NOEMPLOYE),
   FOREIGN KEY(NOTOURNEE) REFERENCES TOURNEE(NOTOURNEE),
   FOREIGN KEY(NOFONCTION) REFERENCES FONCTION(NOFONCTION),
   FOREIGN KEY(NOSITE) REFERENCES Site(NOSITE)
);

CREATE TABLE DETAILDEPOT(
   NOCENTRE INT,
   NOTOURNEE INT,
   NOTYPEDECHET INT,
   QUANTITEDEPOSEE INT,
   PRIMARY KEY(NOCENTRE, NOTOURNEE, NOTYPEDECHET),
   FOREIGN KEY(NOCENTRE) REFERENCES CENTRETRAITEMENT(NOCENTRE),
   FOREIGN KEY(NOTOURNEE) REFERENCES TOURNEE(NOTOURNEE),
   FOREIGN KEY(NOTYPEDECHET) REFERENCES TYPEDECHET(NOTYPEDECHET)
);

CREATE TABLE DETAILDEMANDE(
   NODEMANDE VARCHAR(50),
   NOTYPEDECHET INT,
   QUANTITEENLEVEE INT,
   REMARQUE VARCHAR(50),
   PRIMARY KEY(NODEMANDE, NOTYPEDECHET),
   FOREIGN KEY(NODEMANDE) REFERENCES Demande(NODEMANDE),
   FOREIGN KEY(NOTYPEDECHET) REFERENCES TYPEDECHET(NOTYPEDECHET)
);
