drop table CAMION cascade constraints PURGE;
drop table DEMANDE cascade constraints PURGE;
drop table DETAILDEMANDE cascade constraints PURGE;
drop table DETAILDEPOT cascade constraints PURGE;
drop table ENTREPRISE cascade constraints PURGE;
drop table EMPLOYE cascade constraints PURGE;
drop table FONCTION cascade constraints PURGE;
drop table SITE cascade constraints PURGE;
drop table TOURNEE cascade constraints PURGE;
drop table TYPEDECHET cascade constraints PURGE;
drop table INDISPONIBILITER cascade constraints PURGE;
drop table LICENCIER cascade constraints PURGE;
drop table DEMANDEATRAITER cascade constraints PURGE;
drop table CENTRETRAITEMENT cascade constraints PURGE;
DROP SEQUENCE seq_table_demande;
DROP SEQUENCE seq_table_tournee;
